### PR TITLE
Upgrade to Docusarus 2.2.0

### PR DESCRIPTION
**Pull request by CoWinkKeyDinkInc**
This website has been using an Alpha version of Docusaurus 2 (Alpha 54) for a very long time and I think it's time to upgrade it now since I have trouble starting up the website all of a sudden. The website still has exactly the same functionality, with headers, darkmode/lightmode, imageswitching, etc.

~The only issue left is upgrading the theming inside the `src/theme` folder, which hopefully isn't too tricky finding equivalents like `useLogo();`.~ Any idea where this custom theme we use might have come from @Indicardo? We would also have to get a new API key for search which stopped indexing items back in February.

### CODE REVIEW

**Comment by CoWinkKeyDinkInc** [comment]
https://docusaurus.io/docs/styling-layout#css-in-js

**Comment by CoWinkKeyDinkInc** [comment]
# Comparison between new and old docs
https://imgur.com/a/qs7yncs

There's still a few styling issues left:
- [ ] Fix `<code>` margins
- [ ] Fix `<label>` size (code in red)
- [ ] Center navbar and footer
- [ ] Remove navigation above the title
- [ ] Increase margins in the document body

**Comment by CoWinkKeyDinkInc** [comment]
After editing the CSS files, the new website is almost visually identical. I've decided to keep in the breadcrumbs and the differing appearance of the sidebar since I thought they were better and good additions. All that's left add in the search bar!

**Comment by Indicardo** [comment]
Good job!

**Pull request merged**
